// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Tt5beNAYDvxEciGYIqlq66x1TXjtCxk',
    appId: '1:9120970461:web:4623d93a666c1d69358d34',
    messagingSenderId: '9120970461',
    projectId: 'homework4-a7107',
    authDomain: 'homework4-a7107.firebaseapp.com',
    storageBucket: 'homework4-a7107.appspot.com',
    measurementId: 'G-4H8LN92GFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu93pLvdCz8gDD45mUlt1p-O_NzAy3008',
    appId: '1:9120970461:android:7a358b9883b93f09358d34',
    messagingSenderId: '9120970461',
    projectId: 'homework4-a7107',
    storageBucket: 'homework4-a7107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApPuDKmKls65t-OhZJZpAzW1gp5erwPUM',
    appId: '1:9120970461:ios:1daedbd3b096870d358d34',
    messagingSenderId: '9120970461',
    projectId: 'homework4-a7107',
    storageBucket: 'homework4-a7107.appspot.com',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApPuDKmKls65t-OhZJZpAzW1gp5erwPUM',
    appId: '1:9120970461:ios:63db1d18d213397c358d34',
    messagingSenderId: '9120970461',
    projectId: 'homework4-a7107',
    storageBucket: 'homework4-a7107.appspot.com',
    iosBundleId: 'com.example.hw4.RunnerTests',
  );
}
